n1 = input('Digite algo: ')
print('O tipo primitivo é:{}'.format(type(n1)))
print('So tem espaços? {}'.format(n1.isspace()))
print('É numerico? {}'.format(n1.isnumeric()))
print('So uma letra? {}'.format(n1.isalpha()))